name: "Filter Apps"
description: "Pushes built artifacts to Docker"

inputs:
  workspace:
    description: “package name”
    required: true
  working-directory:
    description: “directory”
    required: true

runs:
  using: "composite"
  steps:
#     - name: Checkout
#       uses: actions/checkout@v3
#       with:
#         fetch-depth: 0
    - name: changed in last commit?
      id: hasChanged
      uses: Trampoline-CX/action-turbo-changed@v1
      with:
        workspace: ${{ inputs.workspace }}
        from: HEAD^1 
        working-directory: ${{ inputs.working-directory }}

#     - name: Validate Action Output
#       id: validateChange
#       if: steps.hasChanged.outputs.changed == 'true'
#       shell: bash  
#       run: CHANGED={{ inputs.workspace }} >> $GITHUB_OUTPUT
