name: "Filter Apps"
description: "Pushes built artifacts to Docker"

inputs:
  workspace:
    description: “package name”
    required: false
  working-directory:
    description: “directory”
    required: false

runs:
  using: "composite"
  steps:
    - name: changed in last commit?
      id: hasChanged
      uses: Trampoline-CX/action-turbo-changed@v1
      with:
        workspace: ${{ inputs.workspace }}
        from: HEAD^1 
        working-directory: ${{ inputs.working-directory }}
        
    - name: Validate Action Output
      id: validateChange
      if: steps.hasChanged.outputs.changed == 'true'
      shell: bash  
      run: CHANGED={{ inputs.workspace }} >> $GITHUB_OUTPUT
